spotify:
  auth:
    endpoint: https://accounts.spotify.com/authorize
    clientId: b07659c8338143f98ded7683fd1d13c5
    redirectUri: http://localhost:8080
    scopes: user-read-email%20app-remote-control

spring:
  data:
    mongodb:
      database: votedo
      uri: mongodb+srv://rgquiet:xkbW4kf32WAJplDC@test-ut4xi.mongodb.net/test?retryWrites=true&w=majority
